### ISSUE TITLE
Releasing TNT v1.0.0

### ISSUE THREAD

**Issue by alexsax** [pytorch/tnt#103]
What do you guys think about releasing a stable version of TNT? @szagoruyko @barrykui 
I use TNT a lot in my own research, but custom versions that fit my projects. It might make sense to release a flexible, stable version that folks can extend. It might also make it easier for people to contribute to TNT. 

### Regarding visualization and metrics:
Some example of what I personally might like to see is:
- A flexible way of dumping results to meters.
- Using meters to serialize results to disk and to log to Visdom

`MeterLogger` is a great idea, and I think that we could probably factor it into a `MeterStorage` class and then a `VisdomMeterLogger` class and also a `FileMeterLogger` class.

### Engines
Is anything happening with engines? Is this a big use case for TNT users? It seems that `pytorch/ignite` has similar classes, but I'm not very familiar with them.

I don't have a very strong opinion on this, but if people are not very interested in the `engines` then it might be useful to drop support for them and to instead focus on I/O and metrics.

**Comment by szagoruyko** [comment]
@alexsax I agree focusing on meters is a good idea. Also, we could look into differences between scipy like #54, and perhaps make scipy a dependency?

regarding engines, there is very little code, we can keep it as is.

**Comment by vfdev-5** [comment]
@alexsax yes in `pytorch/ignite` we have a similar `Engine` class to run over a dataset multiple times. 
Anyway, its very interesting what you are proposing with I/O and metrics 👍
