### ISSUE TITLE
Replace loss[0] with loss.item() due to deprecation

### ISSUE THREAD

**Issue by sauercrowd** [pytorch/tnt#108]
When using tnt's meterlogger a deprecation warning by PyTorch does appear:
```
UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.
5. Use tensor.item() to convert a 0-dim tensor to a Python number
```
Issued by [this line](https://github.com/pytorch/tnt/blob/33677fd4ccdadac4f5e272370a4afc24eaa4f55e/torchnet/logger/meterlogger.py#L101).

Replacing `loss[0]` with `loss.item()` should fix that without any further consequences

**Comment by nbro** [comment]
This also occurs with the MNIST with Visdom example.

**Comment by honghanchenchh** [comment]
Pytorch 1.1.0,  error occurs with the mnist_with_meterlogger example   and it must fix [https://github.com/pytorch/tnt/blob/33677fd4ccdadac4f5e272370a4afc24eaa4f55e/torchnet/logger/meterlogger.py#L101](url)
"IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number"

mnist_with_visdom example can be fixed
`
    def on_forward(state):
        classerr.add(state['output'].data,
                     torch.LongTensor(state['sample'][1]))
        confusion_meter.add(state['output'].data,
                            torch.LongTensor(state['sample'][1]))
        # meter_loss.add(state['loss'].data[0])
        meter_loss.add(state['loss'].item())
`

**Comment by szagoruyko** [comment]
@honghanchenchh wasn't it fixed by #113 ?

**Comment by sauercrowd** [comment]
It should, closing it for now

**Comment by banderlog** [comment]
It fixed in repo but not in python package `torchnet-0.0.4` (last version)
