### ISSUE TITLE
Feature-Request: Ability to save metric-values

### ISSUE THREAD

**Issue by sauercrowd** [pytorch/tnt#109]
It might be useful to be able to save the metrics to files, in order to be able to use them somewhere else for e.g. visualisation.

I'm thinking about something like:
```python
mlog.save_meter(dir='train_metrics', meters={'loss':'loss.csv', 'accuracy':'accuracy.csv', 'confusion':'confusion.csv'})
```

For me that would be really beneficial, what do you think about it?

**Comment by alexsax** [comment]
Yes I agree that this is an important feature! tnt.utils.ResultsWriter does log values to a file and may be what you’re looking for.

FYI In future versions this class will be renamed to “tnt.logger.FileLogger” since the class fits logging semantics.

**Comment by sauercrowd** [comment]
Sorry, didn't see that! Looks really promising and I think that should be exactly what I need
