### ISSUE TITLE
why first point in a different trace in module VisdomPlotLogger? Can we fix it?

### ISSUE THREAD

**Issue by pauking** [pytorch/tnt#114]
this is comment in origin code  in module VisdomPlotLogger
# For some reason, the first point is a different trace. So for now
 # we can just add the point again, this time on the correct curve.

**Comment by CaiusMF** [comment]
Bump!

![extra_trace_value](https://user-images.githubusercontent.com/71214877/99707926-cf404c00-2aa5-11eb-814d-3984f4e58e0e.png)

**Comment by CaiusMF** [comment]
Found workaround: specify the legend in opts when creating VisdomPlotLogger object.

plot_logger = VisdomPlotLogger("line", opts={'legend': ['x', 'y']})
