### ISSUE TITLE
Duplicate classes for Datasets 

### ISSUE THREAD

**Issue by chsasank** [pytorch/tnt#13]
We have two base classes for datasets both in pytorch and torchnet.

1. [`torch.utils.data.Dataset`](http://pytorch.org/docs/data.html#torch.utils.data.Dataset)
2. [`tochnet.dataset.Dataset`](https://github.com/pytorch/tnt/blob/master/torchnet/dataset/dataset.py#L5)

This is also the case for `TensorDataset`. This is potentially confusing for a new user. I had to look up the code to see if there's any relation or difference between the two versions. 

My proposal for solving this is:
1. Use `torch.utils.data.Dataset` as baseclass for all the datasets in tnt. This might mean foregoing of `batch`, `transform` etc. methods, but I think they're actually confusing anyway.
2. Copy the code `tochnet.dataset.TensorDataset` to `torch.utils.data.TensorDataset` and ditch `tochnet.dataset.TensorDataset`

Sasank.

**Comment by apaszke** [comment]
I agree this is confusing and we've been planning to discuss that next week. Sorry for that.

Thanks for the suggestions!
