### ISSUE TITLE
Is APMeter working correct way?

### ISSUE THREAD

**Issue by BeardedWhale** [pytorch/tnt#132]
From doc:
> The APMeter measures the average precision per class.

Consider example:

``` 
output = torch.tensor([[0.1000, 0.9000],
        [0.1000, 0.9000],
        [0.1000, 0.9000],
        [0.1000, 0.9000]])


target = torch.tensor([[1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.]])

```

From my understanding of what was written in doc, I should have:

**accuracies:**
class 0  0
class 1  100%

**precision:**
class 0  0
class 1  50%

So, I run the following code expecting to get [0, 0.5] as output:

```
>> class_meter = torchnet.meter.APMeter()
>> class_error.add(output, target)
>> class_error.value()
tensor([0.7095, 0.5000])
```
What these numbers  mean??? 

So, I try to understand what are these numbers run the sklearn classification report 

```
>> from sklearn.metrics import classification_report
>> print(classification_report(torch.argmax(target, dim=1), torch.argmax(output, dim=1)))

             precision    recall  f1-score   support
           0       0.00      0.00      0.00         2
           1       0.50      1.00      0.67         2
    accuracy                           0.50         4
   macro avg       0.25      0.50      0.33         4
weighted avg       0.25      0.50      0.33         4

```

No such numbers, wonder what this function is doing, definitely not: 
> the average precision per class.

Am I missing something? 👀

**Comment by NguyenVanThanhHust** [comment]
Yeah. you can take a look at their source code [https://github.com/pytorch/tnt/blob/master/torchnet/meter/apmeter.py](url). Line 120. 

You should reshape your input for which each column is an instance, num row is number of class. . For example, I modify your code and get result:

`
def test_sklearn_function():
    probs = torch.tensor([[0.1000, 0.9000],
        [0.1000, 0.9000],
        [0.1000, 0.9000],
        [0.1000, 0.9000]])

    truth = torch.tensor([[1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.]])

    print('sk mean AP: %6.2f\n' % (average_precision_score(truth, probs) * 100))

def test_torchnet_function():
    probs = torch.tensor([[0.1000, 0.9000],
        [0.1000, 0.9000],
        [0.1000, 0.9000],
        [0.1000, 0.9000]])
    probs = torch.reshape(probs, (probs.shape[1], probs.shape[0]))

    truth = torch.tensor([[1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.]])

    truth = torch.reshape(truth, (truth.shape[1], truth.shape[0]))
    
    new_apmeter = APMeter()
    new_apmeter.add(probs, truth)
    best_map = new_apmeter.value().mean()
    print(' torch mean AP: %6.2f\n' % best_map * 100)



if __name__ == "__main__":
    test_sklearn_function()
    print(100*"-")
    test_torchnet_function()
`

and get result:

sk mean AP:  50.00
--------
torch mean AP:   0.50
