### ISSUE TITLE
Preference: PyTorch Tensors or Numpy Arrays

### ISSUE THREAD

**Issue by amdegroot** [pytorch/tnt#18]
I have ported over a few more of the lua torchnet meters and would like to make a PR, but I am curious as to whether I should check inputs and convert to pytorch tensors or check inputs and convert to numpy arrays?  I see more cases of the latter, but my meters are currently using pytorch tensors and resizing tensor storage in `meter.add()` as many of the lua meters do.

**Comment by szagoruyko** [comment]
@amdegroot I think meters should take pytorch tensors by default (optionally numpy too), and use whatever's more convenient inside, numpy or pytorch.

**Comment by amdegroot** [comment]
Ok sweet, just created the PR.
