### ISSUE TITLE
Multiple hooks on the same event

### ISSUE THREAD

**Issue by ethanluoyc** [pytorch/tnt#32]
Would it be better if there can be multiple hooks bound to the same event? This would prevent the need to create a `meta-hook` for all hooks that need to be bound a particular event.

Also what is the relationship between this repo and the trainer class in pytorch?

**Comment by alykhantejani** [comment]
I think the trainer in pytorch is going to be deprecated in favour of tnt (see [here](https://github.com/pytorch/pytorch/issues/2258))
