### ISSUE TITLE
Incorrect documentation for APMeter

### ISSUE THREAD

**Issue by arunmallya** [pytorch/tnt#33]
https://github.com/pytorch/tnt/blob/master/torchnet/meter/apmeter.py#L36-L37 states 
`The probabilities should sum to one over all classes`, which is not a requirement. If multiple classes are present in an image, we would want our method to produce high confidences for each and each confidence is in the [0, 1] range. I don't think normalizing scores across classes would make much sense.

The rest of the implementation doesn't seem to be making use of this requirement.

**Comment by erobic** [comment]
Does this mean that APMeter is good for multi-label classification too? Since it computes AP for each  label, it should work when images may be associated with multiple labels right?
