### ISSUE TITLE
How can I use aucmeter?

### ISSUE THREAD

**Issue by bemoregt** [pytorch/tnt#40]
Hi, @ezyang @zdevito @colesbury @Alexandersax @joeyhng 

How can I use aucmeter in my pytorch?

I'm using a binary classification with pytorch cnn.

Thanks in advance.

**Comment by soumith** [comment]
closed because of all the unwarranted tagging of multiple people (that's not cool, especially this many people!).

**Comment by soumith** [comment]
you can use https://discuss.pytorch.org
