### ISSUE TITLE
Suggestion: Installation by conda install command

### ISSUE THREAD

**Issue by henrych4** [pytorch/tnt#61]
Thanks for creating the module. However, it seems that we cannot install it in conda environment. Will it be supported later? Thank you.

**Comment by szagoruyko** [comment]
what do you mean? you can install it with:

```
pip install git+https://github.com/pytorch/tnt
```

**Comment by henrych4** [comment]
It will be more convenient for those without permission. conda install does not require permission while pip install does.

**Comment by soumith** [comment]
pip install in a conda environment does not require permission

**Comment by Cadene** [comment]
@henrych4 you can try `pip install --user git+https://github.com/pytorch/tnt`

**Comment by henrych4** [comment]
Thanks, I am able to use it now.
