### ISSUE TITLE
PEP8 compliance?

### ISSUE THREAD

**Issue by RadZaeem** [pytorch/tnt#65]
I notice sometimes snake_case, sometimes mixedCase are used for class methods
```python
def on_end_epoch(state):
        mlog.printMeter(mode="Train", iepoch=state['epoch'])
        mlog.resetMeter(mode="Train", iepoch=state['epoch'])
```
WIll tnt codebase 100% comply with PEP8?

**Comment by szagoruyko** [comment]
thanks for pointing it out, meter logger was merged recently, the rest of tnt should be fine.
