### ISSUE TITLE
Incorrect documentation for ConfusionMeter

### ISSUE THREAD

**Issue by granmirupa** [pytorch/tnt#70]
It says [here](https://github.com/pytorch/tnt/blob/master/torchnet/meter/confusionmeter.py):
>  It does not support multi-label, multi-class problems: for such problems, please use MultiLabelConfusionMeter.

Actually, there is no MultiLabelConfusionMeter class implemented in pytorch yet.

**Comment by szagoruyko** [comment]
thanks for spotting! we should add it.

**Comment by shayansiddiqui** [comment]
Hi,

   Any idea when will this be added?

Thanks

**Comment by tsaizehua** [comment]
Hi, when will MultiLabelConfusionMeter be added? Thanks!

**Comment by touqir14** [comment]
I have issued a [PR](https://github.com/pytorch/tnt/pull/137) that implements the MultiLabelConfusionMeter class
