### ISSUE TITLE
AverageValueMeter does not work correctly when using n>1

### ISSUE THREAD

**Issue by srivasv** [pytorch/tnt#71]
If we start using `AverageValueMeter.add` with `n>1` it gives a mean of `NaN`. This is because `self.mean_old` is initialized to `np.nan` and is not reset as we never reach the point of `self.n==1`

**Comment by szagoruyko** [comment]
sorry about that. can you send a PR with a fix?

**Comment by zepinglee** [comment]
I think setting `self.mean_old` to 0.0 is ok.

**Comment by zepinglee** [comment]
BTW the current `add(value, n)` method adds `n` numbers whose sum is `value`. It is not like the `AverageMeter.update(val, n)` in [pytorch/examples/imagenet/main.py](https://github.com/pytorch/examples/blob/master/imagenet/main.py#L284) which adds `n` copies of `val` to internal `self.sum`. Is this a bug?

**Comment by srivasv** [comment]
I will create a PR soon.

@zepinglee it may involve a bit more work than setting the `mean_old` to 0 as the meter also tracks the variance. In any case I'll send out a PR soon.

Also I think that supplying the `sum` of `n` numbers was the way it was done in lua torchnet - so I don't think it is a bug. As long as it is documented as such.
