### ISSUE TITLE
Incorrect assertation in torchnet/meter/confusionmeter.py

### ISSUE THREAD

**Issue by niaoyu** [pytorch/tnt#79]
Incorrect assertation will shown when the target shape is 1 (means only one input per batch).

line43-44：
        assert predicted.shape[0] == target.shape[0], \
            'number of targets and predicted outputs do not match'

Example:
![image](https://user-images.githubusercontent.com/23436844/36777875-047c2634-1ca6-11e8-9674-6e0e3fceed94.png)

this will cause an error in my program

**Comment by Zzmonica** [comment]
I have the same bug as you've proposed, wish to see the way to solve it.

**Comment by alexsax** [comment]
The number of targets should match the size of your batch. I'm assuming that you're using a batch size of 1?  I believe that ConfusionMeter expects a prediction of the shape `NxK` where N is the batch size. Even when using a batch size of one, `predicted` and `target should be 2D arrays. 

Does this fix the problem?
```python
predicted = np.array([predicted])
target = np.array([predicted])
```

**Comment by Zzmonica** [comment]
Actually,my batch size is 1,maybe thats the problem.
Thanks for your answer!
