### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by shubhamjain0594** [pytorch/tnt#9]
On running pip install torchnet in python2.7 environment I get 

```
Collecting torchnet
  Could not find a version that satisfies the requirement torchnet (from versions: )
No matching distribution found for torchnet
```

Pytorch is installed in the environment.

**Comment by soumith** [comment]
torchnet is not on pypi yet. you have to install from source for now.

**Comment by shubhamjain0594** [comment]
```
pip install git+https://github.com/pytorch/tnt.git@master
``` 

This works. Should I add it to README?

**Comment by soumith** [comment]
yes that'd be great.
