### ISSUE TITLE
visdomlogger.py fails because of Visdom.updateTrace() removal

### ISSUE THREAD

**Issue by wojtekcz** [pytorch/tnt#93]
Commit bfbe7a79a19caaabf6b93ef6488b3185cf889e1c removed Visdom.updateTrace()

https://github.com/facebookresearch/visdom/commit/5e1a28f740741ad265beb9fff00127631fbe6e11

This causes the visdomlogger.py to fail.

<ipython-input-24-d12617338b7e> in plot(self, x, y)
     51 
     52     def plot(self, x, y):
---> 53         self.avg_train_loss_logger.log(x, y)
     54 
     55     def record(self, e, loss):

/usr/local/lib/python3.6/dist-packages/torchnet/logger/visdomlogger.py in log(self, *args, **kwargs)
    157             # For some reason, the first point is a different trace. So for now
    158             # we can just add the point again, this time on the correct curve.
--> 159             self.log(*args, **kwargs)
    160 
    161 

/usr/local/lib/python3.6/dist-packages/torchnet/logger/visdomlogger.py in log(self, *args, **kwargs)
    137                     type(self)))
    138             x, y = args
--> 139             self.viz.updateTrace(
    140                 X=np.array([x]),
    141                 Y=np.array([y]),

AttributeError: 'Visdom' object has no attribute 'updateTrace'`

**Comment by alexsax** [comment]
The current version of TNT should support the stable version of visdom available through `pip`. Do you know if this commit made it to the stable version of visdom, yet?

In any case, TNT should prepare for the breaking change in Visdom's API.

**Comment by Luckick** [comment]
Same issue: https://github.com/facebookresearch/visdom/issues/358

The administrator said that: 
The updateTrace function was deprecated over six months ago, and was removed in 5e1a28f

**Comment by alexsax** [comment]
Then I guess it's time to accept PR #94 :) Thanks!
